env:
  browser: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {}
globals:
  LOCAL_DATE_OPTIONS: readonly
  readMore: readonly
  useLol: writable
  color: readonly
  q3: readonly
